drop table if exists tb_client cascade;
drop table if exists tb_order cascade;
drop table if exists tb_order_item cascade;
drop table if exists tb_product cascade;

create table tb_client
(
    id    bigint generated by default as identity,
    email varchar(255) not null,
    name  varchar(255) not null,
    city  varchar(255) not null,
    home_number  varchar(255) not null,
    phone_number  varchar(255) not null,
    state  varchar(255) not null,
    street_name  varchar(255) not null,
    zip_code  varchar(255) not null,
    primary key (id)
);

create table tb_order
(
    id        bigint generated by default as identity,
    moment    timestamp(6) with time zone not null,
    status    smallint                    not null,
    client_id bigint,
    primary key (id)
);

create table tb_order_item
(
    id         bigint generated by default as identity,
    price      float(53) not null,
    quantity   integer   not null,
    order_id   bigint,
    product_id bigint,
    primary key (id)
);

create table tb_product
(
    id    bigint generated by default as identity,
    name  varchar(255) not null,
    price float(53)    not null,
    primary key (id)
);

alter table if exists tb_order
    add constraint FK7c9of0p9ogx0w8sfrebt4n9kk
        foreign key (client_id)
            references tb_client;

alter table if exists tb_order_item
    add constraint FKgeobgl2xu916he8vhljktwxnx
        foreign key (order_id)
            references tb_order;

alter table if exists tb_order_item
    add constraint FK4h5xid5qehset7qwe5l9c997x
        foreign key (product_id)
            references tb_product;


INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Vinicius Augusto', 'vinicius@gmail.com', 'Limeira', '356', '1722939175', 'SP', 'Rua Marina', '12070080');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Augusto Augusto', 'augusto@gmail.com', 'Campinas', '750', '1538556664', 'SP', 'Rua Zaqueu', '11702300');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Roberto Augusto', 'roberto@gmail.com', 'Americana', '336', '1330662716', 'SP', 'Rua Jorlan', '13505142');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Cesar Augusto', 'cesar@gmail.com', 'Piracicaba', '666', '1422775733', 'SP', 'Rua Jacyra', '14710064');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Heloisa Xavier', 'heloisa@gmail.com', 'Cordeiropolis', '777', '1538660653', 'SP', 'Rua Jose', '11088175');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Maria Xavier', 'maria@gmail.com', 'Araras', '483', '1238151303', 'SP', 'Rua Jesus', '07791250');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Giovana Xavier', 'giovana@gmail.com', 'Cosmopolis', '12', '1528545225', 'SP', 'Av Alabama', '08550130');
INSERT INTO tb_client (name, email, city, home_number, phone_number, state, street_name, zip_code)
VALUES ('Raquel Xavier', 'raquel@gmail.com', 'Rio Claro', '046', '1732688818', 'SP', 'Via Tiete', '14106056');

INSERT INTO tb_order (moment, status, client_id)
VALUES ('2021-05-20T23:30:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2021-04-20T19:30:00Z', 1, 1);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2021-03-20T08:30:00Z', 0, 6);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2021-02-20T17:30:00Z', 2, 5);
INSERT INTO tb_order (moment, status, client_id)
VALUES ('2021-01-20T14:30:00Z', 3, 2);

INSERT INTO tb_product (name, price)
VALUES ('TV 4k 50"', 2999.0);
INSERT INTO tb_product (name, price)
VALUES ('PC Gamer RGB', 7800.0);
INSERT INTO tb_product (name, price)
VALUES ('Notebook i9 500gb SSD', 9999.0);
INSERT INTO tb_product (name, price)
VALUES ('Gaming Chair RaceX', 999.0);
INSERT INTO tb_product (name, price)
VALUES ('Mechanical Keyboard Anne Pro 2', 499.9);
INSERT INTO tb_product (name, price)
VALUES ('Pizza', 29.9);

INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 2999.0, 1, 1);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (2, 499.9, 5, 1);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 7800.0, 2, 2);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 999.0, 4, 2);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (5, 29.9, 6, 3);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (2, 499.9, 5, 3);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 9999.0, 3, 4);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (1, 2999.0, 1, 4);
INSERT INTO tb_order_item (quantity, price, product_id, order_id)
VALUES (42, 29.9, 6, 5);
