spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: postgres
    password: orders
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always
